- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      src: service.yml
#       definition: ""
      validate_certs: no
      namespace: default
  - name: Deploy the application
    k8s:
      state: present
      src: deployment.yml
      validate_certs: no
      namespace: default
#       definition: ""
